### ISSUE TITLE
All admonitions are italic

### ISSUE THREAD

**Issue by degville** [canonical-websites/docs.snapcraft.io#35]
See just below *Installing snapd*:
https://discourse-docs.staging.snapcraft.io/t/getting-started/3876

![screenshot_20180920_074601](https://user-images.githubusercontent.com/7047542/45800571-389b5900-bca9-11e8-889c-5ef3dcc6d4b7.png)

**Comment by nottrobin** [comment]
That is Vanilla's blockquote style:

https://docs.vanillaframework.io/en/base/typography#blockquotes-and-citations

To change this, we need to either discuss making an amendment to Vanilla's blockquote style, or stop using blockquotes to display admonitions in forum posts.

**Comment by nottrobin** [comment]
I'm closing this, as the discussion should continue elsewhere, depending on which direction you want to go:

1. My suggestion is that you discuss with the other managers of forum.snapcraft.io using a Discourse plugin to make proper use of the [notifications pattern](https://docs.vanillaframework.io/en/patterns/notification), rather than overloading `<blockquote>`s. Or;
2. If instead you want to discuss changing the base `<blockquote>` style, that would need to be discussed on [the vanilla-framework project](https://github.com/vanilla-framework/vanilla-framework/).

**Comment by degville** [comment]
I've spoken to @niemeyer about this, and the preferred option is to make another exception in the conversion, similar to the way **NOTE TO EDITORS** is  filtered out in `webapp/models.py`.

eg. Look for `[quote]:<symbol>: words [/quote]` and replace with a  Vanilla notification pattern (I'd assume).

**Comment by niemeyer** [comment]
As discussed in the meeting in Berlin, we don't want to avoid making use of plugins that are unknown to people that know Discourse well, even more if there is a good alternative that is simple to use and looks good.

My suggestion is to first figure out in the forum something that is simple and looks nice to people in the forum. Then, let's discuss how that should look like in the processed docs. The actual implementation of that translation is probably the simplest part of it.

**Comment by nottrobin** [comment]
Given that currently Discourse has authority for converting Markdown to HTML, and that this is easily solvable in Discourse, that should really be the place for the solution.

It seems kinda nuts to convert it once onto a `<blockquote>` and then again, somewhere else, into a notification pattern.

The `[note]` plugin is both more semantic, less architecturally less confusing, and avoids potential issues like someone genuinely wanting to write a blockquote that starts with a symbol.

I really think it is much much neater to stay as close as possible to Discourse being entirely responsible for generating HTML from Markdown, and have the app stay as close as possible to faithfully representing the HTML that Discourse provides.

**Comment by niemeyer** [comment]
> Given that currently Discourse has authority for converting Markdown to HTML, and that this is easily solvable in Discourse, that should really be the place for the solution.
>
> It seems kinda nuts to convert it once onto a <blockquote> and then again, somewhere else, into a notification pattern.

Again, we discussed this in Berlin, and we got to an agreement this was the way to go.

> It seems kinda nuts to convert it once onto a <blockquote> and then again, somewhere else, into a notification pattern.

It's a trivial number of lines (2? 5?) in a single application, versus a patch in every single Discourse we have and then teaching people that this syntax renders differently in our discourse than they are used to everywhere else in the world. So I bet to disagree once more, with the exact same rationale used in our meeting in Berlin where _we had already agreed on this direction_.

**Comment by nottrobin** [comment]
Okay it can be done either way, with pros and cons to both. Basically, these represent two philosophical approaches to adding custom functionality, and what we do here will set us down the path to one or the other:

- Only support plain Markdown content in the forum, but add extra functionality to the docs site by post-processing the HTML; or
- Add plugins to Discourse for parsing Markdown into custom HTML, with the docs site naively displaying that HTML

Pros to post-processing:

- All custom functionality is kept in one place - the discourse-docs API plugin
- Discourses don't require any custom plugins (which would have to be kept in sync)

Pros adding plugins to Discourse:

- Forum posts will get the extra functionality, and so look more similar to the documentation site
- Markdown remains semantic - all `[quote]` elements will look the same
- Individual Discourse communities can define the plugins they need

When we discussed the implementation of this previously, we felt that adding plugins to Discourse was the better model in the long-term because we may need more significant customisations, and so it's better to have the forum posts display similarly to the docs site, for a unified experience.

However, I can see I'm unlikely to change your mind on this, so I'll go ahead and post-process as you suggest.
