### ISSUE TITLE
'Interface management' page is not highlighted in navigation

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/docs.snapcraft.io#51]
'Interface management' seems to be the only page that is not highlighted in sidebar navigation when visited:
https://docs.snapcraft.io/t/interface-management/6154

<img width="1031" alt="screen shot 2018-10-12 at 12 51 32" src="https://user-images.githubusercontent.com/83575/46865405-bc1a1700-ce1d-11e8-94ab-e444d91774bb.png">

**Comment by nottrobin** [comment]
This application tries to highlight the current page by simply matching the URL path in the link to the current URL path. Unfortunately, since the navigation is dynamically pulled in, there's not much more that it can do without following literally every link in the navigation, which would take a prohibitively long time.

I believe the only sensible way to solve this is therefore to update the content of [the topic containing the navigation](https://forum.snapcraft.io/t/snap-documentation/3781) to ensure that all the links point to their eventual destination, rather than to redirects.

Since this needs solving on the forum, rather than the codebase, I'm closing this for now. But I'll  update the forum topic to mention that it needs fixing (unfortunately I don't have edit rights).
