### ISSUE TITLE
Table column width

### ISSUE THREAD

**Issue by popey** [canonical-websites/docs.snapcraft.io#58]
https://docs.snapcraft.io/snapcraft-yaml-reference/4276

Visit any page in
the documentation 
which has a table,
and you'll find it 
poorly formatted
and very difficult
to consume. 

Each cell may have
a considerable
amount of text,
but it wraps to
three or four
words per line. 

Like this.

![image](https://user-images.githubusercontent.com/1841272/47689426-cc820e00-dbe1-11e8-9a72-91c24820ea9f.png)

**Comment by degville** [comment]
:+1: It would be great if we could have a more dynamic column width to help mitigate this issue.

The following page may help with testing:
https://docs.snapcraft.io/list-and-table-presentation-ideas/8014#snapcraft

**Comment by nottrobin** [comment]
We would like to limit the number of extensions we make to Discourse's default Markdown support (I know particularly @niemeyer wanted to avoid any plugins at all if possible).

Is there definitely no way this content could be restructure so as to avoid such a deeply nested table?

**Comment by niemeyer** [comment]
Indeed we want to avoid it so that people using the several forums can feel at home with the formatting as it's Discourse-native.

The other side of that picture is that in general these pages would benefit from not being a table in the first place. The example at hand is a good one.. I'd much rather not read all of this content confined to a table column.

I'll catch up with @degville so we can try to find an alternative representation.


The idea I've been discussing with @degville is that these

**Comment by nottrobin** [comment]
In that case, I'll close this for now - discussion can continue in the forum to see if there's a way to restructure the content.

Please file another issue if you decide you do need Markdown extensions.

**Comment by pmahnke** [comment]
@nottrobin 	I think the `table-layout: fixed;`  is the issue

If you do

```css
.l-docs-content {
    width: 72%;
}

.md-table > table {
    table-layout: auto;
}
```

it looks a lot better, but not perfect... someone with more css and flex knowledge could fix that up better


![image](https://user-images.githubusercontent.com/441217/59067518-bc35be00-88a9-11e9-900b-f443233c98b5.png)

**Comment by nottrobin** [comment]
@pmahnke Ah thanks! Yes that looks like a huge improvement.

Enjoying the game?

**Comment by pmahnke** [comment]
@nottrobin no, England lost in the most pathetic of ways... again.
